// Code generated by protoc-gen-go. DO NOT EDIT.
// Stub file for compilation compatibility - replace with generated code when proto is compiled

package pb

import (
	"context"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// UnimplementedDrugInteractionServiceServer is embedded in DrugInteractionGRPCServer
type UnimplementedDrugInteractionServiceServer struct{}

// InteractionCheckRequest represents a request to check drug interactions
type InteractionCheckRequest struct {
	TransactionId       string            `json:"transaction_id"`
	DrugCodes           []string          `json:"drug_codes"`
	PatientContext      *PatientContext   `json:"patient_context,omitempty"`
	CheckOptions        *CheckOptions     `json:"check_options,omitempty"`
	DatasetVersion      string            `json:"dataset_version,omitempty"`
	ExpandClasses       bool              `json:"expand_classes"`
	IncludeContextuals  bool              `json:"include_contextuals"`
	IncludeAlternatives bool              `json:"include_alternatives"`
	IncludeMonitoring   bool              `json:"include_monitoring"`
	SeverityFilter      []string          `json:"severity_filter,omitempty"`
	ClinicalContext     map[string]string `json:"clinical_context,omitempty"`
}

// InteractionCheckResponse represents the response from an interaction check
type InteractionCheckResponse struct {
	TransactionId    string                        `json:"transaction_id"`
	DatasetVersion   string                        `json:"dataset_version"`
	CheckTimestamp   *timestamppb.Timestamp        `json:"check_timestamp"`
	CacheHit         bool                          `json:"cache_hit"`
	RiskScore        float64                       `json:"risk_score"`
	Interactions     []*InteractionDetail          `json:"interactions"`
	AlternativeDrugs map[string]*DrugAlternatives  `json:"alternative_drugs"`
	MonitoringPlan   []*MonitoringRecommendation   `json:"monitoring_plan"`
	Summary          *InteractionSummary           `json:"summary"`
	ConflictTrail    *ConflictTrail                `json:"conflict_trail,omitempty"`
	Recommendations  []string                      `json:"recommendations,omitempty"`
}

// PatientContext provides patient-specific context
type PatientContext struct {
	PatientId       string            `json:"patient_id"`
	Age             int32             `json:"age"`
	Weight          float64           `json:"weight"`
	RenalFunction   float64           `json:"renal_function"`
	HepaticFunction string            `json:"hepatic_function"`
	Conditions      []string          `json:"conditions"`
	GeneticMarkers  map[string]string `json:"genetic_markers"`
	// Fields matching models.PatientContextData
	Pgx           map[string]string `json:"pgx,omitempty"`
	HepaticStage  string            `json:"hepatic_stage,omitempty"`
	RenalStage    string            `json:"renal_stage,omitempty"`
	AgeBand       string            `json:"age_band,omitempty"`
	Comorbidities []string          `json:"comorbidities,omitempty"`
	Allergies     map[string]string `json:"allergies,omitempty"` // Changed to map[string]string
}

// CheckOptions configures interaction checking behavior
type CheckOptions struct {
	IncludeAlternatives bool     `json:"include_alternatives"`
	IncludeMonitoring   bool     `json:"include_monitoring"`
	SeverityFilter      []string `json:"severity_filter"`
	MaxResults          int32    `json:"max_results"`
}

// InteractionDetail describes a single drug interaction
type InteractionDetail struct {
	Drug1Code              string            `json:"drug1_code"`
	Drug2Code              string            `json:"drug2_code"`
	Severity               string            `json:"severity"`
	Mechanism              string            `json:"mechanism"`
	ClinicalEffects        string            `json:"clinical_effects"`
	ManagementStrategy     string            `json:"management_strategy"`
	Evidence               string            `json:"evidence"`
	OnsetDelay             string            `json:"onset_delay"`
	Documentation          string            `json:"documentation"`
	ReferenceUrls          []string          `json:"reference_urls"`
	// Additional fields from server.go usage
	PgxApplicable          bool              `json:"pgx_applicable"`
	DoseAdjustmentRequired bool              `json:"dose_adjustment_required"`
	InteractionId          string            `json:"interaction_id"`
	Confidence             float64           `json:"confidence"`
	Qualifiers             map[string]string `json:"qualifiers"`
	Sources                []string          `json:"sources"`
	TimeToOnset            string            `json:"time_to_onset"`
	Duration               string            `json:"duration"`
	MonitoringParameters   map[string]string `json:"monitoring_parameters"`
	AlternativeDrugs       []string          `json:"alternative_drugs"`
}

// DrugInfo contains drug identification and details
type DrugInfo struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	BrandName string `json:"brand_name"`
	Strength  string `json:"strength"`
	Route     string `json:"route"`
	Form      string `json:"form"`
}

// AlternativeDrug represents a safer alternative drug
type AlternativeDrug struct {
	DrugInfo           *DrugInfo `json:"drug_info"`
	Reason             string    `json:"reason"`
	RequiresMonitoring bool      `json:"requires_monitoring"`
	SafetyScore        float64   `json:"safety_score"`
}

// AlternativeDrugList is a list of alternative drugs
type AlternativeDrugList struct {
	Alternatives []*AlternativeDrug `json:"alternatives"`
}

// MonitoringRecommendation provides monitoring guidance
type MonitoringRecommendation struct {
	Parameter      string   `json:"parameter"`
	Frequency      string   `json:"frequency"`
	Duration       string   `json:"duration"`
	TargetRange    string   `json:"target_range"`
	CriticalValues []string `json:"critical_values"`
	Instructions   string   `json:"instructions"`
}

// InteractionSummary provides summary statistics
type InteractionSummary struct {
	TotalInteractions    int32            `json:"total_interactions"`
	SeverityCounts       map[string]int32 `json:"severity_counts"`
	HighestSeverity      string           `json:"highest_severity"`
	RequiresAction       bool             `json:"requires_action"`
	BlockPrescribing     bool             `json:"block_prescribing"`
	ContraindicatedPairs int32            `json:"contraindicated_pairs"`
	RequiredActions      []string         `json:"required_actions"`
	PgxInteractions      int32            `json:"pgx_interactions"`
	ClassInteractions    int32            `json:"class_interactions"`
	ModifierInteractions int32            `json:"modifier_interactions"`
}

// ConflictTrail tracks conflict resolution and harmonization metadata
type ConflictTrail struct {
	SynthesizedFromVersion string                 `json:"synthesized_from_version"`
	VendorEvidenceIds      []string               `json:"vendor_evidence_ids"`
	OverridesApplied       []string               `json:"overrides_applied"`
	HarmonizedAt           *timestamppb.Timestamp `json:"harmonized_at"`
	HarmonizerVersion      string                 `json:"harmonizer_version"`
}

// DrugAlternatives provides alternative drugs with rationale
type DrugAlternatives struct {
	Rationale    string             `json:"rationale"`
	Alternatives []*AlternativeDrug `json:"alternatives"`
}

// BatchInteractionCheckRequest for batch processing
type BatchInteractionCheckRequest struct {
	Requests []*InteractionCheckRequest `json:"requests"`
	Options  *BatchCheckOptions         `json:"options,omitempty"`
}

// BatchInteractionCheckResponse for batch results
type BatchInteractionCheckResponse struct {
	Responses        []*InteractionCheckResponse `json:"responses"`
	SuccessfulChecks int32                       `json:"successful_checks"`
	FailedChecks     int32                       `json:"failed_checks"`
	Statistics       *BatchProcessingStatistics  `json:"statistics,omitempty"`
	ProcessedAt      *timestamppb.Timestamp      `json:"processed_at,omitempty"`
}

// BatchCheckOptions for batch processing configuration
type BatchCheckOptions struct {
	MaxConcurrency int32 `json:"max_concurrency"`
	TimeoutMs      int64 `json:"timeout_ms"`
	FailFast       bool  `json:"fail_fast"`
	Parallel       bool  `json:"parallel"`
}

// BatchProcessingStatistics provides batch processing metrics
type BatchProcessingStatistics struct {
	StartedAt               *timestamppb.Timestamp `json:"started_at"`
	CompletedAt             *timestamppb.Timestamp `json:"completed_at"`
	TotalRequests           int32                  `json:"total_requests"`
	SuccessfulRequests      int32                  `json:"successful_requests"`
	FailedRequests          int32                  `json:"failed_requests"`
	AverageProcessingTimeMs float64                `json:"average_processing_time_ms"`
	TotalInteractionsFound  int32                  `json:"total_interactions_found"`
}

// FastLookupRequest for quick pairwise checks
type FastLookupRequest struct {
	DrugACode      string `json:"drug_a_code"`
	DrugBCode      string `json:"drug_b_code"`
	DatasetVersion string `json:"dataset_version,omitempty"`
}

// FastLookupResponse for quick pairwise results
type FastLookupResponse struct {
	InteractionFound   bool               `json:"interaction_found"`
	LookupTimeMs       float64            `json:"lookup_time_ms"`
	CacheHit           bool               `json:"cache_hit"`
	Interaction        *InteractionDetail `json:"interaction,omitempty"`
	HasInteraction     bool               `json:"has_interaction"`
	Severity           string             `json:"severity,omitempty"`
	Mechanism          string             `json:"mechanism,omitempty"`
	ClinicalEffects    string             `json:"clinical_effects,omitempty"`
	ManagementStrategy string             `json:"management_strategy,omitempty"`
	Evidence           string             `json:"evidence,omitempty"`
	LookupTimeNs       int64              `json:"lookup_time_ns"`
}

// HealthCheckRequest for health checks
type HealthCheckRequest struct{}

// HealthCheckResponse for health check results
type HealthCheckResponse struct {
	Status            string                      `json:"status"`
	Timestamp         *timestamppb.Timestamp      `json:"timestamp"`
	Components        map[string]*ComponentHealth `json:"components"`
	ComponentHealth   map[string]string           `json:"component_health"`
	Version           string                      `json:"version"`
	DatasetVersion    string                      `json:"dataset_version"`
	TotalInteractions int32                       `json:"total_interactions"`
}

// ComponentHealth describes individual component health
type ComponentHealth struct {
	Status    string                 `json:"status"`
	Message   string                 `json:"message"`
	LastCheck *timestamppb.Timestamp `json:"last_check"`
}

// GetStatisticsRequest for statistics retrieval
type GetStatisticsRequest struct{}

// GetStatisticsResponse for statistics results
type GetStatisticsResponse struct {
	TotalInteractionsInDb int64                  `json:"total_interactions_in_db"`
	UniqueInteractions    int64                  `json:"unique_interactions"`
	ActiveRules           int64                  `json:"active_rules"`
	LastDatasetUpdate     *timestamppb.Timestamp `json:"last_dataset_update"`
	MemoryUsageMb         float64                `json:"memory_usage_mb"`
	CurrentDatasetVersion string                 `json:"current_dataset_version"`
	LookupPerformance     *PerformanceMetrics    `json:"lookup_performance"`
	CacheStatistics       *CacheStatistics       `json:"cache_statistics"`
}

// MatrixStatisticsRequest for matrix statistics
type MatrixStatisticsRequest struct{}

// MatrixStatisticsResponse for matrix statistics results
type MatrixStatisticsResponse struct {
	TotalDrugs            int32                  `json:"total_drugs"`
	TotalInteractions     int32                  `json:"total_interactions"`
	MatrixDensity         float64                `json:"matrix_density"`
	LastUpdated           *timestamppb.Timestamp `json:"last_updated"`
	MemoryUsageMb         float64                `json:"memory_usage_mb"`
	CurrentDatasetVersion string                 `json:"current_dataset_version"`
	LookupPerformance     *PerformanceMetrics    `json:"lookup_performance"`
	CacheStatistics       *CacheStatistics       `json:"cache_statistics"`
}

// PerformanceMetrics for performance statistics
type PerformanceMetrics struct {
	AverageLookupTimeNs int64   `json:"average_lookup_time_ns"`
	CacheHitRate        float64 `json:"cache_hit_rate"`
	TotalLookups        int64   `json:"total_lookups"`
	BatchProcessingRate float64 `json:"batch_processing_rate"`
}

// CacheStatistics for cache metrics
type CacheStatistics struct {
	HotCacheHitRate  float64                `json:"hot_cache_hit_rate"`
	WarmCacheHitRate float64                `json:"warm_cache_hit_rate"`
	HotCacheEntries  int64                  `json:"hot_cache_entries"`
	WarmCacheEntries int64                  `json:"warm_cache_entries"`
	HotCacheMemoryMb float64                `json:"hot_cache_memory_mb"`
	EvictionRate     float64                `json:"eviction_rate"`
	LastRefresh      *timestamppb.Timestamp `json:"last_refresh"`
}

// DrugInteractionServiceServer is the server API interface
type DrugInteractionServiceServer interface {
	CheckInteractions(context.Context, *InteractionCheckRequest) (*InteractionCheckResponse, error)
	BatchCheckInteractions(context.Context, *BatchInteractionCheckRequest) (*BatchInteractionCheckResponse, error)
	FastLookup(context.Context, *FastLookupRequest) (*FastLookupResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	GetMatrixStatistics(context.Context, *MatrixStatisticsRequest) (*MatrixStatisticsResponse, error)
}

// RegisterDrugInteractionServiceServer registers the gRPC service
func RegisterDrugInteractionServiceServer(s interface{}, srv DrugInteractionServiceServer) {
	// Placeholder - replace with generated code
}

// Helper for timestamp conversion
func TimestampFromTime(t time.Time) *timestamppb.Timestamp {
	return timestamppb.New(t)
}
